#!/usr/bin/env node
/**
 * Pull /openapi.json from the running backend and emit TS types.
 *
 * Usage: npm run typegen
 *   API_URL=http://localhost:8000 npm run typegen   # override target
 *
 * Output: src/lib/api-types.ts
 *
 * Run this whenever the FastAPI schema changes. CI fails the typecheck if
 * api-types.ts is stale relative to the running app.
 */

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const apiUrl = process.env.API_URL || process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const outPath = resolve(fileURLToPath(import.meta.url), "../../src/lib/api-types.ts");

const url = new URL("/openapi.json", apiUrl);
console.log(`fetching schema from ${url}`);

const ast = await openapiTS(url, {
  exportType: true,
});

const banner = `/**
 * Auto-generated by scripts/typegen.mjs from FastAPI's /openapi.json.
 * Do not edit by hand — run \`npm run typegen\` instead.
 */
`;

await writeFile(outPath, banner + astToString(ast), "utf8");
console.log(`wrote ${outPath}`);
